version: '2'
services:
  web:
    image: node
    command: npm run dev
    working_dir: /app
    ports:
    - 8080:8080
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    external: true
